<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" class="off">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<?php echo $this->headTitle();?>
<?php
	echo $this->headlink()->prependStylesheet($this->basePath() . '/statics/css/reset.css')
                        ->prependStylesheet($this->basePath() . '/statics/css/system.css');
	echo $this->headScript()
	->prependFile($this->basePath() . '/statics/js/comm.js')
	->prependFile($this->basePath() . '/statics/js/jquery.min.js');
?>
</head>
<body scroll="no">
<?php echo $this->mynavigation('backendNav')->menu()->setPartial('layout/header.phtml');?>
<div id="content">
	<div class="col-left left_menu">
    	<div id="leftMain">
    	<?php echo $this->mynavigation('backendNav')->menu()->setPartial('layout/leftSideBar.phtml');?>
        </div>
        <a href="javascript:;" id="openClose" style="outline-style: none; outline-color: invert; outline-width: medium;" hideFocus="hidefocus" class="open" title="展开与关闭"><span class="hidden">展开</span></a>
    </div>
	<div class="col-1 lf cat-menu" id="display_center_id" style="display:none" height="100%">
		<div class="content">
        	<iframe name="center_frame" id="center_frame" src="" frameborder="false" scrolling="auto" style="border:none" width="100%" height="auto" allowtransparency="true"></iframe>
        </div>
    </div>
    <div class="col-auto mr8">
        <div class="crumbs">
            <div class="shortcut cu-span">
            	<a href="#" target="right"><span>生成首页</span></a>
                <a href="?m=admin&c=cache_all&a=init" target="right"><span>更新缓存</span></a>
                <a href="#"><span>后台地图</span></a></div>
        	当前位置：<span id="current_pos"></span></div>
            <div class="col-1">
                <div class="content" style="position:relative; overflow:hidden">
                    <iframe name="right" id="rightMain" src="index.html" frameborder="false" scrolling="auto" style="overflow-x:hidden;border:none; margin-bottom:30px" width="100%" height="auto" allowtransparency="true"></iframe>
                    <div class="fav-nav">
                        <div id="panellist"></div>
                        <div id="paneladd"><a class="panel-add" href="javascript:add_panel();"><em>添加</em></a></div>
                    </div>
                </div>
            </div>
        </div>
</div>
<script type="text/javascript">
//clientHeight-0; 空白值 iframe自适应高度
function windowW(){
	if($(window).width()<980){
			$('.header').css('width',980+'px');
			$('#content').css('width',980+'px');
			$('body').attr('scroll','');
			$('body').css('overflow','');
	}
}
windowW();
$(window).resize(function(){
	if($(window).width()<980){
		windowW();
	}else{
		$('.header').css('width','auto');
		$('#content').css('width','auto');
		$('body').attr('scroll','no');
		$('body').css('overflow','hidden');

	}
});
window.onresize = function(){
	var heights = document.documentElement.clientHeight-150;document.getElementById('rightMain').height = heights;
	var openClose = $("#rightMain").height()+39;
	$('#center_frame').height(openClose+9);
	$("#openClose").height(openClose+30);
}
window.onresize();
//站点下拉菜单
$(function(){
	//默认载入左侧菜单
	var id = $("li.on", $("#top_menu")).attr('id');
	id = id.substring(2);
	$("#leftMain").load("/index/menu?id="+id);
})

//左侧开关
$("#openClose").click(function(){
	if($(this).data('clicknum')==1) {
		$("html").removeClass("on");
		$(".left_menu").removeClass("left_menu_on");
		$(this).removeClass("close");
		$(this).data('clicknum', 0);
	} else {
		$(".left_menu").addClass("left_menu_on");
		$(this).addClass("close");
		$("html").addClass("on");
		$(this).data('clicknum', 1);
	}
	return false;
});
function _M(menuid,targetUrl) {
	$("#leftMain").load("/index/menu?id="+menuid);
//	if(menuid!=8) {
//		$("#leftMain").load("?m=admin&c=index&a=public_menu_left&menuid="+menuid);
//	} else {
//		$("#leftMain").load("?m=admin&c=phpsso&a=public_menu_left&menuid="+menuid);
//	}

	//$("#rightMain").attr('src', targetUrl);
	$('.top_menu').removeClass("on");
	$('#_M'+menuid).addClass("on");
//	$.get("?m=admin&c=index&a=public_current_pos&menuid="+menuid, function(data){
//		$("#current_pos").html(data);
//	});
	//当点击顶部菜单后，隐藏中间的框架
	$('#display_center_id').css('display','none');
	//显示左侧菜单，当点击顶部时，展开左侧
	$(".left_menu").removeClass("left_menu_on");
	$("#openClose").removeClass("close");
	$("html").removeClass("on");
//	$("#openClose").data('clicknum', 0);
//	$("#current_pos").data('clicknum', 1);
}
function _MP(menuid,targetUrl) {
	$("#rightMain").attr('src', targetUrl);
	$('.sub_menu').removeClass("on fb blue");
	$('#_MP'+menuid).addClass("on fb blue");
	$.get("current_pos_"+menuid+".html", function(data){
		$("#current_pos").html(data+'<span id="current_pos_attr"></span>');
	});
	$("#current_pos").data('clicknum', 1);
}

</script>
</body>
</html>
