<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('css/jquery.cleditor.css'));
$form = $this->form;
$msg = $this->flashMessages();
$id = $form->get('id')->getValue();
?>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation"><a href="<?php echo $this->url('backend' , array('controller' => 'category' , 'action' => 'index'));
    ?>">分类列表</a></li>
  <li role="presentation" class="active"><a href="<?php echo $this
    ->url('backend' , array('controller' => 'category' , 'action' => 'save')) . $id ? '?id='.$id : '';
    ?>"><i class="icon-plus"></i><?php echo $id ? '修改分类' : '添加分类';?></a></li>
</ul>
<br />
<div class="panel panel-default">
  <div class="panel-body">
  <form class="form-horizontal" action="<?php echo $this->url('backend' , array('controller' => 'category' , 'action' => 'save'))?>"
              method="post" enctype="multipart/form-data">
            <?php $img =  $form->get('pic')->getValue();?>
			<fieldset style="border:0;">
			<?php if (!empty($img)):?>
            	<span class="show_image">
            	<img height="150px" src="<?php echo $img;?>" />
            	</span>
            <?php endif;?>
            	<?php echo $this->formHidden($form->get('id'))?>
                <?php echo $this->formText($form->get('name'))?>
                <?php echo $this->formText($form->get('alias'))?>
                <?php echo $this->formFile($form->get('pic'))?>
                <?php echo $this->formText($form->get('keyword'))?>
            	<?php echo $this->formSelect($form->get('parent'))?>
                <?php echo $this->formSelect($form->get('type'))?>
				<?php echo $this->formText($form->get('order'))?>
                <?php echo $this->formSubmit($form->get('submit') , '提交')?>
            </fieldset>
        </form>
  </div>
</div>