<?php
$msg = $this->flashMessages();
?>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="<?php echo $this->url('backend' , array('controller' => 'article' , 'action' => 'index'));
    ?>">文章列表</a></li>
  <li role="presentation"><a href="<?php echo $this->url('backend'
            , array('controller' => 'article' , 'action' => 'save'))?>"><i class="icon-plus"></i>添加文章</a></li>
</ul>
<br />
<div class="panel panel-default">
  <div class="panel-body">
  <form class="form-inline" action="<?php echo $this->url('backend', array('controller'
            => 'article', 'action' => 'index')); ?>" method="get">
                <div class="input-group">
                    <input autocomplete="off" class="input-element span3" value="<?php echo isset($this->k) ? $this->k : '';?>" name="k" type="text">

                <button class="button-element" type="submit">搜索</button>

                </div>
        	</form>
<table class="table" id="table1">
            <thead>
                <tr class="row">
	                <th>全选<input type="checkbox" name="select_all" value="all"/></th>
                    <th key="name" editable="true">
                    <?php if (isset($this->order['title'])):?>
                    <?php $name = $this->order['title'];?>
                    <a href="<?php echo $name['href'];?>">标题<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	标题
                    <?php endif;?>
                    </th>
                    <th key="alias" editable="true">
                     <?php if (isset($this->order['keyword'])):?>
                    <?php $name = $this->order['keyword'];?>
                    <a href="<?php echo $name['href'];?>">关键字<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	关键字
                    <?php endif;?>
 					</th>
                    <th key="keyword" editable="true">
       <?php if (isset($this->order['summary'])):?>
                    <?php $name = $this->order['summary'];?>
                    <a href="<?php echo $name['href'];?>"> 摘要<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 摘要
                    <?php endif;?>
                   </th>
                    <th key="Nick" editable="true">
       <?php if (isset($this->order['category'])):?>
                    <?php $name = $this->order['category'];?>
                    <a href="<?php echo $name['href'];?>">分类<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	分类
                    <?php endif;?>
                    </th>
                    	<th>
      <?php if (isset($this->order['add_time'])):?>
                    <?php $name = $this->order['add_time'];?>
                    <a href="<?php echo $name['href'];?>"> 添加时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	 添加时间
                    <?php endif;?>
                   </th>
                   <th>
      <?php if (isset($this->order['order'])):?>
                    <?php $name = $this->order['order'];?>
                    <a href="<?php echo $name['href'];?>"> 排序<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	排序
                    <?php endif;?>
                    </th>
                   <th>
      <?php if (isset($this->order['last_update'])):?>
                    <?php $name = $this->order['last_update'];?>
                    <a href="<?php echo $name['href'];?>"> 更新时间<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	更新时间
                    <?php endif;?>
                    </th>
                   <!--
                   <th>
      <?php if (isset($this->order['author'])):?>
                    <?php $name = $this->order['author'];?>
                    <a href="<?php echo $name['href'];?>"> 作者<i class="<?php echo $name['class'];?>">&nbsp;</i></a>
                    <?php else:?>
                    	作者
                    <?php endif;?>
                    </th>
                    -->
                    <th>操作</th>
                </tr>
            </thead>
            <tbody>
                <?php $startNumber = $this->startNumber;foreach ($this->paginaction as $item): ?>
                    <tr class="row" primary_value="<?php echo $item->id; ?>">
                    	<td><input type="checkbox" name="select" value="<?php echo $item->id; ?>" data-key="标题" data-value="<?php echo $item->title; ?>" /><?php echo $startNumber++;?></td>
                        <td key="title" editable="true"><?php echo $item->title; ?></td>
                        <td key="keyword" editable="true"><?php echo $item->keyword; ?></td>
                        <td key="summary" editable="true"><?php echo $item->summary; ?></td>
                        <td key="category" editable="true"><?php echo ''//$item->parent_name; ?></td>
                        <td><?php echo date('Y-m-d', strtotime($item->add_time)); ?></td>
                        <td><?php echo $item->order; ?></td>
                        <td><?php echo $item->last_update; ?></td>
                        <td>
                        <a class="btn btn-edit" href="<?php echo $this->url('backend', array('controller'
                                => 'article', 'action' => 'save')) ?>?id=<?php echo $item->id;?>">
                                <i class="icon-edit"></i>编辑
                            </a>
                            <a class="btn btn-delete" href="<?php echo $this->url('backend', array('controller'
                                => 'article', 'action' => 'delete')) ?>?id=<?php echo $item->id;?>"><i class="icon-delete"></i>删除
                         </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        <?php echo $this->paginationControl($this->paginaction,'Sliding','layout/pagination' , array('link'
            => $this->url('backend' , array('controller' => 'article' , 'action' => 'index')).'?'.$this->query));?>
  </div>
</div>
<div id="dialog" title="筛选" style="display: none;">
	<form id="frmFilter">
		<div class="filter_item">
			<div class="filter_label"></div>
			<div class="filter_opt">
			</div>
			<div class='filter_val'><input value="" type="text" name="filter_value" /></div>
			<div class='condition_opt'><span class='add_c'>+</span></div>
			<div style='clear: both;'>&nbsp;</div>
		</div>
	</form>
</div>
<script type="text/javascript">
<!--
var productEditableParam={
		'postUrl':'/index/updateColumn',
		'primary_key':'UserID',
		'table':'MemberTable',
// 		'isShow':{
// 			type:'radio',
// 	        group:{
// 	            1:'显示',
// 	            0:'不显示'
// 	        }
// 		},
// 		'order':{
// 			type:'text',
// 			reg: /^\d+$/,
// 			tip:'只能为数字!'
// 		},
		'UserName':{
			type:'text',
			reg:/^[a-zA-Z0-9_]{3,16}$/,
			tip:'格式不正确：3-16个字母、数字或下划线组成'
		},
		'Email':{
			type:'text',
			reg:/^[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*$/,
			tip:'邮箱格式不正确'
		},
		'Mobile':{
			type:'text',
			reg:/^((\+86)|(86))?(1(3|5|8))\d{9}$/,
			tip:'手机号码格式不正确'
		},
		'Nick':{
			type:'text'
		},
		'Points':{
			type:'text',
			reg:/^[0-9]+(\.[0-9]{1,2})?$/,
			tip:'格式不正确'
		}
	};
var options={
		tableID:'table1',
		editableParam:productEditableParam
}
// new Editable(options,$("#table1"));
var url = '<?php echo $this->url('backend' , array('controller' => 'category' , 'action' => 'index'));?>';
var query = '<?php echo $this->filterQuery?>';
$(function(){
	var select_field = [
	        			{name: 'UserName', vtype:'string',ctype:'text',html:'分类名称'},
	        			{name: 'Email', vtype:'string',ctype:'text',html:'邮箱'},
	        			{name: 'Mobile',vtype:'string',ctype:'text',html:'手机'},
	        			{name: 'Nick',vtype:'string',ctype:'text',html:'昵称'},
	        			{name: 'Points',vtype:'int',ctype:'text','html':'积分'},
	        			{name: 'Gender',vtype:'int',ctype:'radio',html:'性别'},
	        			{name: 'LoginCount',vtype:'int',ctype:'text',html:'登录次数'}
	        	    ];
    filter.init(select_field);
	$("#selector").click(function(){
		$("#dialog").dialog({position:'center',width:500,buttons: [ { text: "确定", click: function() {

			var query = filter.getQuery();
			location.href=url+'?'+query;
			 $( this ).dialog( "close" );
			} } ]});
	});
	var memory_list = getcookie('memory_id_list');
	var strs = memory_list.split(',');
	for (i=0;i<strs.length ;i++ )
    {
		$("input[type='checkbox'][name='select'][value='"+strs[i]+"']").click();
    }
})
//-->
</script>