<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet($this->basePath('styles/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('styles/jquery.cleditor.css'));
$form = $this->form;
$user = $this->user;
$msg = $this->flashMessages();
?>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation" class="active"><a href="<?php echo $this
    ->url('backend' , array('controller' => 'member' , 'action' => 'pwd')) . $form->get('UserID')->getValue() ? "?id=".$form->get('UserID')->getValue() : '';
    ?>"><i class="icon-plus"></i>修改密码</a></li>
</ul>
<br />
<div class="panel panel-default">
  <div class="panel-body">
  <form class="form-horizontal" action="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'pwd')).'?id='.$form->get('UserID')->getValue();?>"
              method="post" enctype="multipart/form-data">
            <fieldset>
            <div class="form-group">
	            <label for="UserName" class="col-sm-2 control-label">用户名</label>
	            <div class="col-sm-7">
	            <?php echo $user['UserName'];?>
	            </div>
            </div>
            	<?php echo $this->formHidden($form->get('UserID'))?>
            	<?php echo $this->formText($form->get('Password'))?>
                <?php echo $this->formText($form->get('rePassword'))?>
                <?php echo $this->formSubmit($form->get('submit') , '提交')?>
            </fieldset>
        </form>
  </div>
</div>
<script>
$(function() {
	$(".btn-submit").click(function(){
		$("input[type='submit'][class='button-element']").trigger('click');
	});
})
</script>