<?php
$this->headScript()->appendFile($this->basePath('js/jquery-ui-1.10.2.custom.min.js'))
->appendFile($this->basePath('js/jquery.cleditor.min.js'))
->appendFile($this->basePath('js/jquery.ui.datepicker-zh-CN.js'));
$this->headLink()->appendStylesheet($this->basePath('css/jquery-ui-1.10.2.custom.min.css'))
->appendStylesheet($this->basePath('css/jquery.cleditor.css'));
$form = $this->form;
$msg = $this->flashMessages();
$userid = $form->get('UserID')->getValue();
?>
<ul class="nav nav-tabs" role="tablist">
  <li role="presentation"><a href="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'index'));
    ?>">会员列表</a></li>
  <li role="presentation" class="active"><a href="<?php echo $this
    ->url('backend' , array('controller' => 'member' , 'action' => 'save')) . $userid ? '?id='.$userid : '';
    ?>"><i class="icon-plus"></i><?php echo $userid ? '修改帐号' : '添加帐号';?></a></li>
</ul>
<br />
<div class="panel panel-default">
  <div class="panel-body">
  <form class="form-horizontal" action="<?php echo $this->url('backend' , array('controller' => 'member' , 'action' => 'save'))?>"
              method="post" enctype="multipart/form-data">
            <?php $img =  $form->get('ImgUrl')->getValue();?>
			<fieldset style="border:0;">
			<?php if (!empty($img)):?>
            	<span class="show_image">
            	<img height="150px" src="<?php echo $img;?>" />
            	</span>
            <?php endif;?>
            	<?php echo $this->formHidden($form->get('UserID'))?>
                <?php echo $this->formText($form->get('UserName'))?>
                <?php //echo $this->formText($form->get('Password'))?>
                <?php echo $this->formText($form->get('Nick'))?>
                <?php echo $this->formFile($form->get('ImgUrl'))?>
                <?php echo $this->formText($form->get('Points'))?>
            	<?php echo $this->formSelect($form->get('Province'))?>
                <?php echo $this->formSelect($form->get('City'))?>
                <?php echo $this->formSelect($form->get('District'))?>
                <?php echo $this->formText($form->get('Address'))?>
            	<?php echo $this->formText($form->get('Email'))?>
                <?php echo $this->formText($form->get('Mobile'))?>
            	<?php echo $this->formText($form->get('Tel'))?>
            	<?php echo $this->formSelect($form->get('Gender'))?>
            	<?php echo $this->formText($form->get('Birthday'))?>
                <?php echo $this->formText($form->get('QQ'))?>
                <?php echo $this->formText($form->get('MSN'))?>
                <?php echo $this->formSelect($form->get('Status'))?>
                <?php echo $this->formHidden($form->get('Source'));?>


                <?php echo $this->formSubmit($form->get('submit') , '提交')?>
            </fieldset>
        </form>
  </div>
</div>
<script>
var options = {prov : "select[name='Province']", city : "select[name='City']", dist : "select[name='District']"};
new Area(options);
$(function() {
	$("input[name='Birthday']").datepicker();
	$(".btn-submit").click(function(){
		$("input[type='submit'][class='button-element']").trigger('click');
	});
	$(".btn-reset").click(function(){
		$("input[type='reset'][class='button-element']").trigger('click');
	});
})
</script>