<div class="box">
    <div class="box-header">
        <h2><i class="icon-box"></i>更新完成</h2>
        <div class="t_top">
        <p  class='t_right'>
        <a class="btn btn-return" href="<?php echo $this->url('backend' 
            , array('controller' => 'resource' , 'action' => 'index'))?>">
        <i class="icon-plus"></i>返回</a>
        </p>
        </div>
    </div>
	<div class="box-content">
	<table class="table">
        <thead>
            <tr class="row">
            	<th width="50">序号</th>
                <th width="180">资源名</th>
            </tr>
        </thead>
        <tfoot>
            <tr class="row">
            	<th width="50">序号</th>
                <th width="180">资源名</th>
            </tr>
        </tfoot>
        <tbody>
        	<?php foreach($this->re as $k=>$v):?>
	<tr>
		<td><?php echo $k+1;?></td>
		<td><?php echo $v?></td>
	<?php endforeach;?>
        </tbody>
    </table>
	</div>
</div>
